// Generated by gencpp from file speechrecognition/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SPEECHRECOGNITION_MESSAGE_ADDTWOINTS_H
#define SPEECHRECOGNITION_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <speechrecognition/AddTwoIntsRequest.h>
#include <speechrecognition/AddTwoIntsResponse.h>


namespace speechrecognition
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace speechrecognition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::speechrecognition::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::speechrecognition::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::speechrecognition::AddTwoInts > {
  static const char* value()
  {
    return "speechrecognition/AddTwoInts";
  }

  static const char* value(const ::speechrecognition::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::speechrecognition::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::speechrecognition::AddTwoInts > 
template<>
struct MD5Sum< ::speechrecognition::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::speechrecognition::AddTwoInts >::value();
  }
  static const char* value(const ::speechrecognition::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::speechrecognition::AddTwoIntsRequest> should match 
// service_traits::DataType< ::speechrecognition::AddTwoInts > 
template<>
struct DataType< ::speechrecognition::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::speechrecognition::AddTwoInts >::value();
  }
  static const char* value(const ::speechrecognition::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::speechrecognition::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::speechrecognition::AddTwoInts > 
template<>
struct MD5Sum< ::speechrecognition::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::speechrecognition::AddTwoInts >::value();
  }
  static const char* value(const ::speechrecognition::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::speechrecognition::AddTwoIntsResponse> should match 
// service_traits::DataType< ::speechrecognition::AddTwoInts > 
template<>
struct DataType< ::speechrecognition::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::speechrecognition::AddTwoInts >::value();
  }
  static const char* value(const ::speechrecognition::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPEECHRECOGNITION_MESSAGE_ADDTWOINTS_H
